Repository infinum/eightshift-forms, pull requests merged in 2022-05, with the labels that each got.

#226 Mailer update
  src/Mailer/Mailer.php
  src/Mailer/SettingsMailer.php
  tests/Mailer/MailerSettingsTest.php
Labels: improvement

#231 Change URLs to work with multisite
  src/Blocks/custom/form-selector/components/form-selector-options.js
  src/Blocks/custom/form/components/form-options.js
  src/Blocks/custom/forms/components/forms-options.js
  src/Blocks/custom/goodbits/components/goodbits-options.js
  src/Blocks/custom/greenhouse/components/greenhouse-options.js
  src/Blocks/custom/hubspot/components/hubspot-options.js
  src/Blocks/custom/mailchimp/components/mailchimp-options.js
  src/Blocks/custom/mailerlite/components/mailerlite-options.js
  src/Blocks/manifest.json
  src/Editor/Editor.php
  src/Enqueue/Blocks/EnqueueBlocks.php
  src/Helpers/Helper.php
  tests/Helpers.php
  tests/Helpers/HelperTest.php
Labels: bugfix

#233 Add apply filters to geolocation disabling
  src/Geolocation/Geolocation.php
Labels: feature request, improvement
