Repository infinum/eightshift-forms, pull requests merged in 2022-02, with the labels that each got.

#206 Feature/recaptcha
  eightshift-forms.php
  src/Blocks/components/admin-settings-section/admin-settings-section-admin.scss
  src/Blocks/components/form/assets/form.js
  src/Blocks/components/form/assets/index.js
  src/Enqueue/Theme/EnqueueTheme.php
  src/Hooks/Filters.php
  src/Hooks/Variables.md
  src/Hooks/Variables.php
  src/Integrations/Goodbits/SettingsGoodbits.php
  src/Integrations/Greenhouse/SettingsGreenhouse.php
  src/Integrations/Hubspot/SettingsHubspot.php
  src/Integrations/Mailchimp/SettingsMailchimp.php
  src/Integrations/Mailerlite/SettingsMailerlite.php
  src/Labels/Labels.php
  src/Rest/Routes/AbstractBaseRoute.php
  src/Rest/Routes/FormSubmitCaptchaRoute.php
  src/Validation/SettingsCaptcha.php
Labels: improvement

#207 added auto-init settings
  eightshift-forms.php
  src/Blocks/components/form/assets/form.js
  src/Blocks/components/form/assets/index.js
  src/Enqueue/Theme/EnqueueTheme.php
  src/Hooks/Form.md
  src/Settings/Settings/SettingsGeneral.php
Labels: improvement

#209 WP 5.9 readonly deprecated fix
  src/Blocks/components/checkbox/checkbox.php
  src/Blocks/components/input/input.php
  src/Blocks/components/textarea/textarea.php
Labels: bugfix

#210 Bump Frontend Libs version
  package-lock.json
Labels: dependencies

#211 Add Category Taxonomy to Forms
  src/CustomPostType/Forms.php
Labels: feature request

#215 Geolocation logic init fix
  src/Geolocation/Geolocation.php
Labels: bugfix

#216 Feature/uploads
  eightshift-forms.php
  package-lock.json
  src/Blocks/assets/application-editor.js
  src/Blocks/assets/styles/application-editor.scss
  src/Blocks/components/file/file.php
  src/Blocks/components/form/assets/form.js
  src/Blocks/components/form/assets/index.js
  src/Blocks/components/select/select.php
  src/Blocks/components/textarea/textarea.php
  src/Blocks/custom/forms/forms.php
  src/Editor/Editor.php
  src/Enqueue/Blocks/EnqueueBlocks.php
  src/Geolocation/Geolocation.php
  src/Helpers/UploadHelper.php
  src/Hooks/Filters.php
  src/Integrations/ClientInterface.php
  src/Integrations/Goodbits/GoodbitsClient.php
  src/Integrations/Greenhouse/GreenhouseClient.php
  src/Integrations/Hubspot/HubspotClient.php
  src/Integrations/Mailchimp/MailchimpClient.php
  src/Integrations/Mailchimp/MailchimpClientInterface.php
  src/Integrations/Mailerlite/MailerliteClient.php
  src/Mailer/Mailer.php
  src/Rest/Routes/AbstractBaseRoute.php
  src/Rest/Routes/AbstractFormSubmit.php
  src/Rest/Routes/FormSubmitGoodbitsRoute.php
  src/Rest/Routes/FormSubmitGreenhouseRoute.php
  src/Rest/Routes/FormSubmitHubspotRoute.php
  src/Rest/Routes/FormSubmitMailchimpRoute.php
  src/Rest/Routes/FormSubmitMailerRoute.php
  src/Rest/Routes/FormSubmitMailerliteRoute.php
  webpack.config.js
Labels: bugfix, improvement
